#!/usr/bin/Rscript

options(repos=structure(c(CRAN="http://cran.revolutionanalytics.com")))

install.packages("ade4", dependencies=c("Depends", "Suggests"))
install.packages("R2HTML", dependencies=c("Depends", "Suggests"))
install.packages("fracdiff", dependencies=c("Depends", "Suggests"))
install.packages("clusterSim", dependencies=c("Depends", "Suggests"))
install.packages("data.table", dependencies=c("Depends", "Suggests"))
install.packages("forecast", dependencies=c("Depends", "Suggests"))
install.packages("geoR", dependencies=c("Depends", "Suggests"))
install.packages("stringr", dependencies=c("Depends", "Suggests"))
install.packages("lubridate", dependencies=c("Depends", "Suggests"))
install.packages("Matrix", dependencies=c("Depends", "Suggests"))
install.packages("plyr", dependencies=c("Depends", "Suggests"))
install.packages("reshape", dependencies=c("Depends", "Suggests"))
install.packages("twitteR", dependencies=c("Depends", "Suggests"))
install.packages("vegan", dependencies=c("Depends", "Suggests"))
install.packages("XML", dependencies=c("Depends", "Suggests"))
install.packages("gtable", dependencies=c("Depends", "Suggests"))
install.packages("proto", dependencies=c("Depends", "Suggests"))
install.packages("munsell", dependencies=c("Depends", "Suggests"))
install.packages("labeling", dependencies=c("Depends", "Suggests"))
install.packages("ggplot2", dependencies=c("Depends", "Suggests"))
